%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\Git\mocs_proto\DesignDocuments\MultiMOCS_IO_List_R0.01.xlsx
%    Worksheet: Common module
%
% Auto-generated by MATLAB on 2025-11-24 09:21:08

%% Set up the Import Options and import the data
optsC = spreadsheetImportOptions("NumVariables", 37);

% Specify sheet and range
optsC.Sheet = "Common module";
optsC.DataRange = "A3";

% Specify column names and types
optsC.VariableNames = ["No", "CH", "VarName3", "VarName4", "TagNo", "SignalType", "VarName7", "VarName8", "VarName9", "Description", "Range", "VarName12", "VarName13", "Alarm", "VarName15", "VarName16", "VarName17", "VarName18", "ConnectionPoint", "Remark", "VarName21", "CAT4", "CAT4VName", "IDX", "InterfaceTag", "VarName26", "S01", "No1", "ToModule", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37"];
optsC.VariableTypes = ["categorical", "double", "double", "double", "string", "categorical", "categorical", "categorical", "categorical", "string", "string", "double", "string", "double", "double", "double", "double", "double", "categorical", "categorical", "categorical", "categorical", "string", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify variable properties
optsC = setvaropts(optsC, ["TagNo", "Description", "Range", "VarName13", "CAT4VName", "InterfaceTag", "VarName26", "S01", "No1", "ToModule", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37"], "WhitespaceRule", "preserve");
optsC = setvaropts(optsC, ["No", "TagNo", "SignalType", "VarName7", "VarName8", "VarName9", "Description", "Range", "VarName13", "ConnectionPoint", "Remark", "VarName21", "CAT4", "CAT4VName", "InterfaceTag", "VarName26", "S01", "No1", "ToModule", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37"], "EmptyFieldRule", "auto");

%% Set up the Import Options and import the data
optsI = spreadsheetImportOptions("NumVariables", 37);

% Specify sheet and range
optsI.Sheet = "No.# Module";
optsI.DataRange = "A2:AK88";

% Specify column names and types
optsI.VariableNames = ["No", "CH", "VarName3", "VarName4", "TagNo", "SignalType", "VarName7", "VarName8", "VarName9", "Description", "Range", "VarName12", "VarName13", "Alarm", "VarName15", "VarName16", "VarName17", "VarName18", "ConnectionPoint", "Remark", "VarName21", "CAT4", "CAT4VName", "IDX", "InterfaceTag", "VarName26", "S01", "No1", "ToModule", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "FODosing"];
optsI.VariableTypes = ["categorical", "double", "double", "double", "string", "categorical", "categorical", "categorical", "categorical", "string", "string", "string", "categorical", "double", "double", "string", "string", "double", "categorical", "categorical", "categorical", "categorical", "string", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify variable properties
optsI = setvaropts(optsI, ["TagNo", "Description", "Range", "VarName12", "VarName16", "VarName17", "CAT4VName", "InterfaceTag", "VarName26", "S01", "No1", "ToModule", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "FODosing"], "WhitespaceRule", "preserve");
optsI = setvaropts(optsI, ["No", "TagNo", "SignalType", "VarName7", "VarName8", "VarName9", "Description", "Range", "VarName12", "VarName13", "VarName16", "VarName17", "ConnectionPoint", "Remark", "VarName21", "CAT4", "CAT4VName", "InterfaceTag", "VarName26", "S01", "No1", "ToModule", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "FODosing"], "EmptyFieldRule", "auto");
