
PROGRAM _INIT
	(* Insert code here *)
	StructTest;
	IF_MON;
	IF_PARA;		// Shutdown
	IF_PARA_Comm;	// Shutdown
	IF_PARA_CSys;	// Generated
	IF_PARA_CFlag;	// Generated
	IF_PARA_CMain;	// Generated
	IF_PARA_CFODS;	// Generated
	IF_PARA_CReserved;	// Generated
	IF_PARA_No1FF;
	IF_PARA_No1FB;
	IF_PARA_No1Reserved;
	IF_PARA_No2FF;
	IF_PARA_No2FB;
	IF_PARA_No2Reserved;
	IF_PARA_No3FF;
	IF_PARA_No3FB;
	IF_PARA_No3Reserved;
	IF_PARA_No4FF;
	IF_PARA_No4FB;
	IF_PARA_No4Reserved;
	IF_PARA_No5FF;
	IF_PARA_No5FB;
	IF_PARA_No5Reserved;
	IF_PARA_No6FF;
	IF_PARA_No6FB;
	IF_PARA_No6Reserved;
	IF_PARA_No7FF;
	IF_PARA_No7FB;
	IF_PARA_No7Reserved;
	IF_PARA_No8FF;
	IF_PARA_No8FB;
	IF_PARA_No8Reserved;
END_PROGRAM

PROGRAM _CYCLIC
	(* Insert code here *)
//	StructTest;
//	IF_MON;
END_PROGRAM

PROGRAM _EXIT
	(* Insert code here *)
	 
END_PROGRAM

